name: fleet
channels:
- defaults
- pytorch
dependencies:
- python=3.9
- pytorch=1.12.1
- torchvision=0.13
#- cudatoolkit=11.7
- pip
- numpy
- jupyter
- matplotlib
- scikit-learn
- scipy
- pandas
- seaborn
- nltk
- h5py
- spacy                            
- unidecode
- pip:
  - future
  - tb-nightly
  - gym
  - pillow
  - kaggle
  - ipywidgets
  - tqdm>=4.60
  - pyquaternion>=0.9
  - numpy-quaternion~=2022.4.2
  - dataclass-wizard~=0.22.2
  - importlib-metadata
  - opencv-python
  - dropbox==11.36.0
  - typer~=0.7.0
  - pyproj==3
  - plotly==5.11.0
  - ipykernel>=5
  - zod[cli]
  - imageio
  - timezonefinder
  - flwr[simulation]
  - pyyaml
  - psycopg2
  - sqlparse
  - tqdm
  - numba
  - networkx
  - torchsummary
  - Flask 